version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: npm install
      - run: npm run start
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  cypress:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: npm install
      - run: npm run cy:run
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - cypress